- name: install lamp
  apt: name={{item}} state=latest update_cache=yes
  with_items:
    - apache2
    - php5
    - libapache2-mod-suphp
    - php5-dev
    - php5-curl
    - php5-cgi
    - php5-cli
    - php5-gd
    - php5-mysql
