---
  - name: mailcatcher
    gem: name=mailcatcher state=latest

  - name: configure php email
    command: sed -ir "s/;\?sendmail_path =.*/sendmail_path = \/usr\/bin\/env \/usr\/local\/bin\/catchmail/" /etc/php5/apache2/php.ini
    command: sed -ir "s/;\?sendmail_path =.*/sendmail_path = \/usr\/bin\/env \/usr\/local\/bin\/catchmail/" /etc/php5/cli/php.ini
    when: php is defined and php == True

  - name: kill mailcatcher
    command: pkill mailcatcher
    ignore_errors: yes

  - name: run mailcatcher
    command: mailcatcher --http-ip 192.168.69.69
